SET SID=%3
SET PID=%4
SET PPID=%5
SET PARENT_SID=%6
SET PARENT_PID=%7
SET PARENT_PPID=%8
SET CURR_CONTEXT=%TEMP%\RaccineUserContext\RaccineYaraContext-%SID%-%PID%-%PPID%.txt
SET PARENT_CONTEXT=%TEMP%\RaccineUserContext\RaccineYaraContext-%PARENT_SID%-%PARENT_PID%-%PARENT_PPID%.txt

SET YARA_DEFINES=
IF EXIST %CURR_CONTEXT% SET /p YARA_DEFINES=<%CURR_CONTEXT%

SET PARENT_YARA_DEFINES=
IF EXIST %PARENT_CONTEXT% SET /p PARENT_YARA_DEFINES=<%PARENT_CONTEXT%

SETLOCAL ENABLEDELAYEDEXPANSION

SET ALL_YARA_DEFINES=%YARA_DEFINES% %PARENT_YARA_DEFINES%
"%ProgramFiles%\Raccine\yara64.exe" %ALL_YARA_DEFINES% %1 %2 >> %2.out
